version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./cmd/app/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DB_PASSWORD=postgres

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
