server:
  host: "localhost"
  port: "8000"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "filmoteka"
  sslmode: "disable"
  password: "postgres"

redis:
  addr: "localhost:6379"
  db: "0"